export interface ElementStyle{
  alignContent: any
  alignItems: any
  alignSelf: any
  alignmentBaseline: any
  all: any
  animation: any
  animationDelay: any
  animationDirection: any
  animationDuration: any
  animationFillMode: any
  animationIterationCount: any
  animationName: any
  animationPlayState: any
  animationTimingFunction: any
  backfaceVisibility: any
  background: any
  backgroundBlendMode: any
  backgroundClip: any
  backgroundColor: any
  backgroundImage: any
  backgroundPosition: any
  backgroundPositionX: any
  backgroundPositionY: any
  backgroundRepeat: any
  backgroundRepeatX: any
  backgroundRepeatY: any
  backgroundSize: any
  baselineShift: any
  border: any
  borderBottom: any
  borderBottomColor: any
  borderBottomLeftRadius: any
  borderBottomRightRadius: any
  borderBottomStyle: any
  borderBottomWidth: any
  borderCollapse: any
  borderColor: any
  borderImage: any
  borderImageOutset: any
  borderImageRepeat: any
  borderImageSlice: any
  borderImageSource: any
  borderImageWidth: any
  borderLeft: any
  borderLeftColor: any
  borderLeftStyle: any
  borderLeftWidth: any
  borderRadius: any
  borderRight: any
  borderRightColor: any
  borderRightStyle: any
  borderRightWidth: any
  borderSpacing: any
  borderStyle: any
  borderTop: any
  borderTopColor: any
  borderTopLeftRadius: any
  borderTopRightRadius: any
  borderTopStyle: any
  borderTopWidth: any
  borderWidth: any
  bottom: any
  boxShadow: any
  boxSizing: any
  bufferedRendering: any
  captionSide: any
  clear: any
  clip: any
  clipPath: any
  clipRule: any
  color: any
  colorInterpolation: any
  colorInterpolationFilters: any
  colorRendering: any
  content: any
  counterIncrement: any
  counterReset: any
  cursor: any
  cx: any
  cy: any
  direction: any
  display: any
  dominantBaseline: any
  emptyCells: any
  fill: any
  fillOpacity: any
  fillRule: any
  filter: any
  flex: any
  flexBasis: any
  flexDirection: any
  flexFlow: any
  flexGrow: any
  flexShrink: any
  flexWrap: any
  float: any
  floodColor: any
  floodOpacity: any
  font: any
  fontFamily: any
  fontKerning: any
  fontSize: any
  fontStretch: any
  fontStyle: any
  fontVariant: any
  fontVariantLigatures: any
  fontWeight: any
  glyphOrientationHorizontal: any
  glyphOrientationVertical: any
  height: any
  imageRendering: any
  isolation: any
  justifyContent: any
  left: any
  letterSpacing: any
  lightingColor: any
  lineHeight: any
  listStyle: any
  listStyleImage: any
  listStylePosition: any
  listStyleType: any
  margin: any
  marginBottom: any
  marginLeft: any
  marginRight: any
  marginTop: any
  marker: any
  markerEnd: any
  markerMid: any
  markerStart: any
  mask: any
  maskType: any
  maxHeight: any
  maxWidth: any
  maxZoom: any
  minHeight: any
  minWidth: any
  minZoom: any
  mixBlendMode: any
  motion: any
  motionOffset: any
  motionPath: any
  motionRotation: any
  objectFit: any
  objectPosition: any
  opacity: any
  order: any
  orientation: any
  orphans: any
  outline: any
  outlineColor: any
  outlineOffset: any
  outlineStyle: any
  outlineWidth: any
  overflow: any
  overflowWrap: any
  overflowX: any
  overflowY: any
  padding: any
  paddingBottom: any
  paddingLeft: any
  paddingRight: any
  paddingTop: any
  page: any
  pageBreakAfter: any
  pageBreakBefore: any
  pageBreakInside: any
  paintOrder: any
  perspective: any
  perspectiveOrigin: any
  pointerEvents: any
  position: any
  quotes: any
  r: any
  resize: any
  right: any
  rx: any
  ry: any
  shapeImageThreshold: any
  shapeMargin: any
  shapeOutside: any
  shapeRendering: any
  size: any
  speak: any
  src: any
  stopColor: any
  stopOpacity: any
  stroke: any
  strokeDasharray: any
  strokeDashoffset: any
  strokeLinecap: any
  strokeLinejoin: any
  strokeMiterlimit: any
  strokeOpacity: any
  strokeWidth: any
  tabSize: any
  tableLayout: any
  textAlign: any
  textAlignLast: any
  textAnchor: any
  textDecoration: any
  textIndent: any
  textOverflow: any
  textRendering: any
  textShadow: any
  textTransform: any
  top: any
  touchAction: any
  transform: any
  transformOrigin: any
  transformStyle: any
  transition: any
  transitionDelay: any
  transitionDuration: any
  transitionProperty: any
  transitionTimingFunction: any
  unicodeBidi: any
  unicodeRange: any
  userZoom: any
  vectorEffect: any
  verticalAlign: any
  visibility: any
  whiteSpace: any
  widows: any
  width: any
  willChange: any
  wordBreak: any
  wordSpacing: any
  wordWrap: any
  writingMode: any
  x: any
  y: any
  zIndex: any
  zoom: any
}
